In [2]:
# PASSO 1 - IMPORTAR A BASE DE DADOS 

import pandas as pd

tabela_vendas = pd.read_excel("vendas\Vendas.xlsx")

display(tabela_vendas)

<>:5: SyntaxWarning: "\V" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\V"? A raw string is also an option.
<>:5: SyntaxWarning: "\V" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\V"? A raw string is also an option.
C:\Users\mathe\AppData\Local\Temp\ipykernel_5204\1089545915.py:5: SyntaxWarning: "\V" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\V"? A raw string is also an option.
  tabela_vendas = pd.read_excel("vendas\Vendas.xlsx")

,Cód.,Data,Loja,Produto,Quantidade,Valor Unitário
0,1,5/18/2022,Maranhão,Caixa de som,4,79
1,2,7/24/2022,Santa Catarina,Notebook,9,3789
2,3,12/20/2022,Rio de Janeiro,Notebook,3,3789
3,4,1/22/2022,Espírito Santo,Nobreak,9,1279
4,5,9/11/2022,Tocantins,Impressora,9,699
...,...,...,...,...,...,...
14995,14996,8/18/2022,São Paulo,Webcam,4,150
14996,14997,1/6/2022,São Paulo,Impressora,9,699
14997,14998,11/13/2022,São Paulo,Notebook,9,3789
14998,14999,6/29/2022,São Paulo,Caixa de som,6,79
14999,15000,9/5/2022,Minas Gerais,Tablet,3,1349

In [3]:
# PASSO 2 - CALCULAR O PRODULTO MAIS VENDIDO (EM QUANTIDADE)

tb_quantidade_produlto = tabela_vendas.groupby('Produto').sum()

tb_quantidade_produlto = tb_quantidade_produlto[["Quantidade"]]

tb_quantidade_produlto = tb_quantidade_produlto.sort_values(by="Quantidade", ascending=False)

display(tb_quantidade_produlto)

              Quantidade
Produto
Impressora         13285
Notebook           12930
Monitor             9923
Nobreak             6778
Tablet              6684
Teclado             6631
Webcam              6562
Caixa de som        6535
PC                  6518
Mouse               6481

In [4]:
# PASSO 3 - CALCULAR O PRODUTO MAIS VENDIDO (EM FATURAMENTO)

tabela_vendas['Faturamento'] = tabela_vendas['Quantidade'] * tabela_vendas['Valor Unitário']

tb_faturamento_produto = tabela_vendas.groupby('Produto').sum()

tb_faturamento_produto = tb_faturamento_produto[['Faturamento']].sort_values(by='Faturamento', ascending=False)

display(tb_faturamento_produto)

              Faturamento
Produto
Notebook         48991770
PC               38456200
Monitor          11907600
Impressora        9286215
Tablet            9016716
Nobreak           8669062
Teclado           1193580
Webcam             984300
Mouse              725872
Caixa de som       516265

In [5]:
# PASSO 4 - CALCULAR A LOJA/ESTADO QUE MAIS VENDEU (EM FATURAMENTO)

tb_faturamento_loja = tabela_vendas.groupby('Loja').sum()

tb_faturamento_loja = tb_faturamento_loja[['Faturamento']]

tb_faturamento_loja = tb_faturamento_loja.sort_values(by='Faturamento', ascending=False)

display(tb_faturamento_loja)

                     Faturamento
Loja
São Paulo               41018776
Rio de Janeiro          12274351
Minas Gerais            11491527
Paraná                   7611645
Pernambuco               7041123
Rio Grande do Sul        6618703
Goiás                    6288009
Bahia                    5030257
Santa Catarina           4971700
Distrito Federal         4355565
Espírito Santo           3523731
Pará                     2932941
Ceará                    2925202
Mato Grosso do Sul       2009149
Mato Grosso              1708095
Paraíba                  1635059
Amazonas                 1574940
Rio Grande do Norte      1324966
Tocantins                1256281
Piauí                     929292
Maranhão                  924990
Alagoas                   872983
Sergipe                   637378
Rondônia                  358665
Roraima                   173428
Acre                      142254
Amapá                     116570

In [6]:
# PASSO 5 - CALCULAR O TICKET MÉDIO POR LOJA/ESTADO

tabela_vendas['Ticket Médio'] = tabela_vendas['Valor Unitário']

tb_ticket_medio = tabela_vendas.groupby('Loja').mean(numeric_only=True)

tb_ticket_medio = tb_ticket_medio[['Ticket Médio']]

tb_ticket_medio = tb_ticket_medio.sort_values(by='Ticket Médio', ascending=False)

display(tb_ticket_medio)

                     Ticket Médio
Loja
Acre                  2142.769231
Sergipe               1735.333333
Tocantins             1734.306452
Rio Grande do Sul     1690.043909
Pará                  1683.746177
Santa Catarina        1683.562620
Pernambuco            1683.036849
Paraná                1608.725917
Bahia                 1606.045226
Mato Grosso do Sul    1600.952607
Rio de Janeiro        1594.396825
Espírito Santo        1580.024752
Goiás                 1577.605634
São Paulo             1573.686250
Mato Grosso           1572.692708
Piauí                 1571.308511
Maranhão              1561.763158
Ceará                 1540.983871
Minas Gerais          1526.709104
Rio Grande do Norte   1515.595238
Paraíba               1509.593750
Distrito Federal      1504.994393
Amazonas              1486.920904
Alagoas               1430.821138
Roraima               1369.095238
Rondônia              1292.000000
Amapá                  966.600000

In [7]:
# PASSO 6 - CRIAR UM GRAFICO/DASHBOARD DA LOJA/ESTADO QUE MAIS VENDEU ( EM FATURAMENTO)

import plotly.express as px

grafico = px.bar(tb_faturamento_loja, y='Faturamento', x=tb_faturamento_loja.index)

grafico.show()